inherit_gem:
  rubocop-govuk:
    - config/default.yml
AllCops:
  Exclude:
    - 'vendor/**/*'

# This check made lots of false positives where `prerender` methods
# used `||=` to avoid creating duplicate shapes.
Naming/MemoizedInstanceVariableName:
  Enabled: false

# It is unreasonable to forbid single-character variable names. For a
# game, a lot of the time `x`, `y`, etc are good names.
Naming/MethodParameterName:
  Enabled: false
